foo: 
  test: hello
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
spring: 
  redis:
    database: 0
    host: 192.168.218.128
    port: 6379
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000
  zipkin:
    base-url: http://localhost:9411
  slenth:
    sampler:
      percentage: 1.0
logging:
  file: "logs/eureka-${spring.application.name}.log"
